config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes for User authentication
  devise_for :users

  # Custom route for sign out to ensure it uses a GET request
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  # Routes for Logging in (also set root to the login itself)
  root to: 'pages#login'
  get 'login', to: 'pages#login'
  get 'sign_up', to: 'pages#create'
  get 'home', to: 'pages#home'
  get 'card_create', to: 'pages#card_create', as: 'card_create'
  post 'create_card', to: 'pages#create_card', as: 'create_card'
  get 'trading_card/:id', to: 'pages#show_card', as: 'trading_card'
  get 'edit_card/:id', to: 'pages#edit_card', as: 'edit_card'
  patch 'update_card/:id', to: 'pages#update_card', as: 'update_card'
  get 'destroy_card/:id', to: 'pages#destroy_card', as: 'destroy_card'


  # Redirect after sign in or sign up
  devise_scope :user do
    authenticated :user do
      root to: 'pages#home', as: :authenticated_root # Redirect to home page if authenticated
    end

    unauthenticated do
      root to: 'pages#login', as: :unauthenticated_root # Redirect to login page if not authenticated
    end
  end

end

app/views/pages/card_create.html.erb
<!-- app/views/pages/card_create.html.erb -->
<div class="card-create-container">
  <h1>Create a New Trading Card</h1>
  <%= form_with(model: @trading_card, url: create_card_path, local: true, multipart: true) do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
    <div>
      <%= form.label :front_image %><br>
      <%= form.file_field :front_image %>
    </div>
    <div>
      <%= form.label :back_image %><br>
      <%= form.file_field :back_image %>
    </div>
    <div>
      <%= form.label :move1_name %><br>
      <%= form.text_field :move1_name %>
    </div>
    <div>
      <%= form.label :move1_description %><br>
      <%= form.text_area :move1_description %>
    </div>
    <div>
      <%= form.label :move2_name %><br>
      <%= form.text_field :move2_name %>
    </div>
    <div>
      <%= form.label :move2_description %><br>
      <%= form.text_area :move2_description %>
    </div>
    <div>
      <%= form.label :color %><br>
      <%= form.color_field :color %>
    </div>
    <div>
      <%= form.submit 'Create Card' %>
    </div>
  <% end %>
</div>

app/views/pages/create.html.erb
<!-- app/views/pages/create.html.erb -->
<div class="login-container">
  <div class="logo">
    <%= image_tag 'logo.png' %>
  </div>
  <div class="login-card">
    <h1>Sign Up</h1>
    <%= form_for(@resource, as: @resource_name, url: registration_path(@resource_name)) do |f| %>
      <div>
        <%= f.label :username %><br />
        <%= f.text_field :username, autofocus: true %>
      </div>
      <div>
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>
      <div>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      </div>
      <div>
        <%= f.submit "Sign Up" %>
      </div>
    <% end %>
    <%= link_to 'Already have an account? Log In', login_path, class: 'signup-link' %>
  </div>
</div>

app/views/pages/edit_card.html.erb
<!-- app/views/pages/edit_card.html.erb -->
<div class="card-create-container">
  <div class="card-create-card">
    <h1>Edit Trading Card</h1>
    <%= form_with(model: @trading_card, url: update_card_path(@trading_card), local: true, multipart: true) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="form-group">
        <%= form.label :front_image %>
        <%= form.file_field :front_image %>
      </div>
      <div class="form-group">
        <%= form.label :back_image %>
        <%= form.file_field :back_image %>
      </div>
      <div class="form-group">
        <%= form.label :move1_name %>
        <%= form.text_field :move1_name %>
      </div>
      <div class="form-group">
        <%= form.label :move1_description %>
        <%= form.text_area :move1_description %>
      </div>
      <div class="form-group">
        <%= form.label :move2_name %>
        <%= form.text_field :move2_name %>
      </div>
      <div class="form-group">
        <%= form.label :move2_description %>
        <%= form.text_area :move2_description %>
      </div>
      <div class="form-group">
        <%= form.label :color %>
        <%= form.color_field :color %>
      </div>
      <div class="form-group" style="flex: 1 1 100%;">
        <%= form.submit 'Update Card' %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<!-- app/views/pages/home.html.erb -->
<div class="search-container">
  <input type="text" id="search-bar" placeholder="Search by card name or username...">
</div>
<div class="cards-container" id="cards-container">
  <% @recent_cards.each do |card| %>
    <div class="card" style="background-color: <%= card.color %>;" data-name="<%= card.name %>" data-username="<%= card.user.username %>">
      <div class="card-front" data-card-id="<%= card.id %>">
        <h2><%= card.name %></h2>
        <%= image_tag card.front_image, class: 'card-image' %>
        <div class="move">
          <h3><%= card.move1_name %></h3>
          <p><%= card.move1_description %></p>
        </div>
        <div class="move">
          <h3><%= card.move2_name %></h3>
          <p><%= card.move2_description %></p>
        </div>
        <button class="switch-view" data-card-id="<%= card.id %>">Show Back</button>
      </div>
      <div class="card-back" data-card-id="<%= card.id %>" style="display: none; background-color: <%= card.color %>;">
        <%= image_tag card.back_image, class: 'card-image' %>
        <button class="switch-view" data-card-id="<%= card.id %>">Show Front</button>
      </div>
    </div>
  <% end %>
</div>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        console.log("DOM fully loaded and parsed");
        const searchBar = document.getElementById("search-bar");
        const cardsContainer = document.getElementById("cards-container");
        const cards = Array.from(cardsContainer.getElementsByClassName("card"));

        // Attach an event listener to the search bar to detect input changes
        searchBar.addEventListener("input", () => {
            // Get the search query and convert it to lowercase
            const query = searchBar.value.toLowerCase();
            console.log("Search query: ", query);

            // Loop through each card and check if it matches the search query
            cards.forEach(card => {

                // Get the card's name and username from the data attributes and convert them to lowercase
                const name = card.getAttribute("data-name").toLowerCase();
                const username = card.getAttribute("data-username").toLowerCase();

                // Check if the card's name or username includes the search query
                if (name.includes(query) || username.includes(query)) {
                    // If matches display the card
                    card.style.display = "";
                    console.log("Card shown: ", name, username);
                } else {
                    card.style.display = "none";
                    console.log("Card hidden: ", name, username);
                }
            });
        });
    });
</script>

app/views/pages/login.html.erb
<!-- app/views/pages/login.html.erb -->
<div class="login-container">
  <div class="logo">
    <%= image_tag 'logo.png' %>
  </div>
  <div class="login-card">
    <h1>Sign In</h1>
    <%= form_for(User.new, as: :user, url: user_session_path) do |f| %>
      <div>
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>
      <div>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.submit "Sign In" %>
      </div>
    <% end %>
    <%= link_to 'New? Create Account', sign_up_path, class: 'signup-link' %>
  </div>
</div>

app/views/pages/show_card.html.erb
<!-- app/views/pages/show_card.html.erb -->
<div class="recent-cards">
  <h2>Your Recent Cards</h2>
  <div class="cards-container">
    <% @recent_cards.each do |card| %>
      <div class="card" style="background-color: <%= card.color %>;">
        <div class="card-front" data-card-id="<%= card.id %>">
          <h2><%= card.name %></h2>
          <%= image_tag card.front_image, class: 'card-image' %>
          <div class="move">
            <h3><%= card.move1_name %></h3>
            <p><%= card.move1_description %></p>
          </div>
          <div class="move">
            <h3><%= card.move2_name %></h3>
            <p><%= card.move2_description %></p>
          </div>
          <button class="switch-view" data-card-id="<%= card.id %>">Show Back</button>
          <%= link_to 'Edit', edit_card_path(card), class: 'edit-button' %>
          <%= link_to 'Delete', destroy_card_path(card), class: 'delete-button' %>
        </div>
        <div class="card-back" data-card-id="<%= card.id %>" style="display: none; background-color: <%= card.color %>;">
          <%= image_tag card.back_image, class: 'card-image' %>
          <button class="switch-view" data-card-id="<%= card.id %>">Show Front</button>
        </div>
      </div>
    <% end %>
  </div>
</div>