config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Devise routes for User authentication
  devise_for :users

  # Custom route for sign out to ensure it uses a GET request
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  # Routes for Logging in (also set root to the login itself)
  root to: 'pages#login'
  get 'login', to: 'pages#login'
  get 'sign_up', to: 'pages#create'
  get 'home', to: 'pages#home'
  get 'card_create', to: 'pages#card_create', as: 'card_create'
  post 'create_card', to: 'pages#create_card', as: 'create_card'
  get 'trading_card/:id', to: 'pages#show_card', as: 'trading_card'
  get 'edit_card/:id', to: 'pages#edit_card', as: 'edit_card'
  patch 'update_card/:id', to: 'pages#update_card', as: 'update_card'
  get 'destroy_card/:id', to: 'pages#destroy_card', as: 'destroy_card'


  # Redirect after sign in or sign up
  devise_scope :user do
    authenticated :user do
      root to: 'pages#home', as: :authenticated_root # Redirect to home page if authenticated
    end

    unauthenticated do
      root to: 'pages#login', as: :unauthenticated_root # Redirect to login page if not authenticated
    end
  end

end

app/views/layouts/_header.html.erb
<!-- app/views/layouts/_header.html.erb -->
<header class="header">
  <div class="header-left">
    <%= link_to image_tag('TCC.png', alt: 'Logo'), home_path %>
  </div>
  <nav class="header-right">
    <%= link_to 'Create', card_create_path %>
    <%= link_to 'My Cards', current_user.trading_cards.any? ? trading_card_path(current_user.trading_cards.first) : '#', class: current_user.trading_cards.any? ? '' : 'disabled' %>
    <%= link_to 'Log Out', sign_out_path, method: :delete %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'cards' %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/base.html.erb
<!-- app/views/layouts/base.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'cards' %> <!-- Include the JavaScript file for card functionality -->
  </head>

<body>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>